# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RuffDraft' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RuffDraft
  pod 'AppCenter/Crashes', '~> 1.4.0'
  pod 'AppCenter/Analytics', '~> 1.4.0'
  pod 'AppCenterReactNativeShared', '~> 1.3.0'

  

  platform :ios, '9.0'
  target 'RuffDraftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RuffDraft-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RuffDraft-tvOS

  target 'RuffDraft-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
